### importo librerias

In [61]:
import pandas as pd
import numpy as np

### Ejercicio 1: carga del archivo csv y creacion del primer DataFrame

In [62]:
df_arts = pd.read_csv('datos_arts.csv')

In [63]:
df_arts

,grupo,depto,item,articulo,fecha,precio,unidades,importe
0,15 LIMPIEZA DEL HOGAR,CUIDADO DE LA ROPA,1000025719,1000025719 JABON EN BARRA BULL DOG GLICERINA 2...,19/08/2020,54,7.0,378.0
1,15 LIMPIEZA DEL HOGAR,CUIDADO DE LA ROPA,1000025724,1000025724 JABON LIQUIDO PAR D.P. 800 CC NEVEX...,19/08/2020,136,1.0,136.0
2,15 LIMPIEZA DEL HOGAR,CUIDADO DE LA ROPA,1000025752,1000025752 JABON LIQ NEVEX MATIC MULTIAC DIF D...,19/08/2020,410,1.0,410.0
3,15 LIMPIEZA DEL HOGAR,CUIDADO DE SUPERFICIES,1000025907,1000025907 PANO DE PISO STANDARD 50X55 CM,19/08/2020,79,1.0,79.0
4,15 LIMPIEZA DEL HOGAR,CUIDADO DE SUPERFICIES,1000025908,1000025908 REJILLA 37X37CM.,19/08/2020,59,1.0,59.0
...,...,...,...,...,...,...,...,...
63590,15 LIMPIEZA DEL HOGAR,CUIDADO DE LA ROPA,1000187363,1000187363 JABON LIQUIDO DE ROPA PLUMA 800ML,10/11/2020,50,5.0,250.0
63591,3 COMESTIBLES,GOLOSINAS,1000188100,1000188100 ALFAJOR BOCADO BLANCO TATA x 6,10/11/2020,62,5.0,310.0
63592,3 COMESTIBLES,ACEITES Y GRASAS,1000194151,1000194151 ACEITE DE OLIVA OLIVARES DE ROCHA 5...,10/11/2020,240,2.0,480.0
63593,18 PERFUMERIA,CUIDADO CAPILAR,1000215423,1000215423 SHAMPOO HEAD & SHOULDER COCONUT 180 CC,10/11/2020,259,1.0,259.0
63594,18 PERFUMERIA,CUIDADO CORPORAL,1000218721,1000218721 JABON DOVE ANTIBACTERIAL CUIDA Y PR...,10/11/2020,59,5.0,295.0

### Ejercicio 2: obtención de un nuevo DataFrame

In [64]:

df_2 = df_arts[['fecha', 'unidades', 'importe']] # tomo las columnas necesarias
df_2 = df_2.groupby(['fecha']).sum() # realizo el agrupamiento por fechas

In [65]:
df_2

            unidades    importe
fecha
01/09/2020  2344.364  187805.51
01/10/2020  2960.822  217737.20
01/11/2020  3322.844  244827.88
02/09/2020  2871.914  236752.26
02/10/2020  3647.606  280201.06
...              ...        ...
30/08/2020  3783.594  246807.36
30/09/2020  2684.160  188665.76
30/10/2020  3488.152  252455.86
31/08/2020  2957.792  182605.31
31/10/2020  3680.664  287103.04

[84 rows x 2 columns]

### Ejercicio 3: creación de la variable Sector

In [66]:
# creo la lista listacondicion con las condiciones requeridas
# creo la lista eleccion con los valores solicitados
# Creacion de la variable 'sector' que contendra la logica solicitada
listacondicion = [(df_arts ['grupo'] == '15 LIMPIEZA DEL HOGAR') | (df_arts ['grupo'] == '18 PERFUMERIA'),( df_arts ['grupo'] == '4 LACTEOS') | (df_arts ['grupo'] == '9 FIAMBRERIA')]
eleccion = ['NO COMESTIBLES', 'PERECEDEROS']
df_arts ['sector'] = np.select(listacondicion, eleccion, default= df_arts ['grupo'])

In [67]:
df_arts

,grupo,depto,item,articulo,fecha,precio,unidades,importe,sector
0,15 LIMPIEZA DEL HOGAR,CUIDADO DE LA ROPA,1000025719,1000025719 JABON EN BARRA BULL DOG GLICERINA 2...,19/08/2020,54,7.0,378.0,NO COMESTIBLES
1,15 LIMPIEZA DEL HOGAR,CUIDADO DE LA ROPA,1000025724,1000025724 JABON LIQUIDO PAR D.P. 800 CC NEVEX...,19/08/2020,136,1.0,136.0,NO COMESTIBLES
2,15 LIMPIEZA DEL HOGAR,CUIDADO DE LA ROPA,1000025752,1000025752 JABON LIQ NEVEX MATIC MULTIAC DIF D...,19/08/2020,410,1.0,410.0,NO COMESTIBLES
3,15 LIMPIEZA DEL HOGAR,CUIDADO DE SUPERFICIES,1000025907,1000025907 PANO DE PISO STANDARD 50X55 CM,19/08/2020,79,1.0,79.0,NO COMESTIBLES
4,15 LIMPIEZA DEL HOGAR,CUIDADO DE SUPERFICIES,1000025908,1000025908 REJILLA 37X37CM.,19/08/2020,59,1.0,59.0,NO COMESTIBLES
...,...,...,...,...,...,...,...,...,...
63590,15 LIMPIEZA DEL HOGAR,CUIDADO DE LA ROPA,1000187363,1000187363 JABON LIQUIDO DE ROPA PLUMA 800ML,10/11/2020,50,5.0,250.0,NO COMESTIBLES
63591,3 COMESTIBLES,GOLOSINAS,1000188100,1000188100 ALFAJOR BOCADO BLANCO TATA x 6,10/11/2020,62,5.0,310.0,3 COMESTIBLES
63592,3 COMESTIBLES,ACEITES Y GRASAS,1000194151,1000194151 ACEITE DE OLIVA OLIVARES DE ROCHA 5...,10/11/2020,240,2.0,480.0,3 COMESTIBLES
63593,18 PERFUMERIA,CUIDADO CAPILAR,1000215423,1000215423 SHAMPOO HEAD & SHOULDER COCONUT 180 CC,10/11/2020,259,1.0,259.0,NO COMESTIBLES
63594,18 PERFUMERIA,CUIDADO CORPORAL,1000218721,1000218721 JABON DOVE ANTIBACTERIAL CUIDA Y PR...,10/11/2020,59,5.0,295.0,NO COMESTIBLES

In [68]:
# verifico la condicion restante
df_3=df_arts[((df_arts.sector != "NO COMESTIBLES") & (df_arts.sector != "PERECEDEROS"))]
df_3

,grupo,depto,item,articulo,fecha,precio,unidades,importe,sector
158,1 BEBIDAS,BEB. ALCOHOLICAS,1000048181,1000048181 CERVEZA HEINEKEN 1 LITRO NO RET,19/08/2020,158,6.0,948.0,1 BEBIDAS
159,1 BEBIDAS,BEB. ALCOHOLICAS,1000048183,1000048183 CERVEZA SCHNEIDER 1LITRO NO RET,19/08/2020,117,1.0,117.0,1 BEBIDAS
160,1 BEBIDAS,BEB. NO ALCOHOLICAS,1000048217,1000048217 JUGO NECTAR WATT`S NARANJA 400.00 ML,19/08/2020,45,2.0,90.0,1 BEBIDAS
161,1 BEBIDAS,BEB. ALCOHOLICAS,1000048326,1000048326 CERVEZA HEINEKEN LATA 473.00 CC,19/08/2020,81,13.0,1053.0,1 BEBIDAS
162,1 BEBIDAS,BEB. NO ALCOHOLICAS,1000048368,1000048368 JUGO JUMEX DURAZNO + BARRITA DE CER...,19/08/2020,45,1.0,45.0,1 BEBIDAS
...,...,...,...,...,...,...,...,...,...
63587,3 COMESTIBLES,GOLOSINAS,1000185902,1000185902 VALIJA BOCADITO NEGRO PUNTA BALLENA...,10/11/2020,149,1.0,149.0,3 COMESTIBLES
63588,3 COMESTIBLES,GALLETAS,1000186415,1000186415 TOSTADAS DE ARROZ TATA 150G,10/11/2020,79,4.0,316.0,3 COMESTIBLES
63589,3 COMESTIBLES,GALLETAS,1000186416,1000186416 TOSTADITAS DE ARROZ TATA 120G,10/11/2020,55,14.0,770.0,3 COMESTIBLES
63591,3 COMESTIBLES,GOLOSINAS,1000188100,1000188100 ALFAJOR BOCADO BLANCO TATA x 6,10/11/2020,62,5.0,310.0,3 COMESTIBLES
63592,3 COMESTIBLES,ACEITES Y GRASAS,1000194151,1000194151 ACEITE DE OLIVA OLIVARES DE ROCHA 5...,10/11/2020,240,2.0,480.0,3 COMESTIBLES

### Ejercicio 4: obtener un nuevo DataFrame

In [69]:
# realizo el agrupamiento por fecha y sector y genero las columnas precio e importe para ver dichos totales en el agrupamiento
df_group = df_arts.groupby(['fecha','sector']).agg({'precio':'mean', 'importe':'sum'})
df_group

                               precio    importe
fecha      sector
01/09/2020 1 BEBIDAS        96.752688   20815.00
           3 COMESTIBLES    91.644769  109873.00
           NO COMESTIBLES  156.177215   41199.00
           PERECEDEROS     154.333333   15918.51
01/10/2020 1 BEBIDAS        84.051282   26979.00
...                               ...        ...
31/08/2020 PERECEDEROS     107.772727   14038.31
31/10/2020 1 BEBIDAS        98.720000   58302.00
           3 COMESTIBLES    96.333333  138551.00
           NO COMESTIBLES  173.978495   68573.00
           PERECEDEROS     148.388889   21677.04

[336 rows x 2 columns]